//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedexDbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientVaccination
    {
        public int VaccinationID { get; set; }
        public int PatientID { get; set; }
        public System.DateTime VaccinationDate { get; set; }
        public int VaccineID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Vaccine Vaccine { get; set; }
    }
}
