//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedexDbModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vaccine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaccine()
        {
            this.PatientVaccinations = new HashSet<PatientVaccination>();
        }
    
        public int VaccineID { get; set; }
        [Required(ErrorMessage ="Scrie scrie")]
        [MinLength(3, ErrorMessage ="Prea mic!")]
        public string Description { get; set; }
        [Required(ErrorMessage ="Type necesar")]
        public int TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientVaccination> PatientVaccinations { get; set; }
    }
}
